# Generated by Django 5.0.4 on 2024-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_produto', models.FloatField()),
                ('loja_produto', models.TextField()),
                ('descricao_produto', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
    ]
