# Generated by Django 5.0.4 on 2025-02-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0002_alter_pricetracker_dateofsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busca_consolidado',
            fields=[
                ('Consolidadoid', models.IntegerField(primary_key=True, serialize=False)),
                ('SearchString', models.CharField(max_length=100)),
                ('AvgPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateOfSearch', models.DateTimeField()),
            ],
        ),
    ]
