# Generated by Django 5.0.4 on 2025-02-04 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0003_busca_consolidado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busca_consolidado',
            table='Busca_consolidado',
        ),
        migrations.AlterModelTable(
            name='pricetracker',
            table='PriceTracker_temp',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products_temp',
        ),
    ]
