# Generated by Django 5.0.4 on 2025-02-04 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0004_alter_busca_consolidado_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('price_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrecoMedioApp.pricetracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Favorites',
                'unique_together': {('user', 'price_tracker')},
            },
        ),
    ]
