# Generated by Django 5.0.4 on 2025-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0005_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
