# Generated by Django 5.2 on 2025-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0006_alter_favorites_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco_Mensal',
            fields=[
                ('Consolidadoid', models.IntegerField(primary_key=True, serialize=False)),
                ('SearchString', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
            ],
            options={
                'db_table': 'Preco_Mensal',
            },
        ),
    ]
