# Generated by Django 5.0.4 on 2025-05-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0008_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='SearchString',
            field=models.CharField(default='', max_length=100),
        ),
    ]
