# Generated by Django 5.0.4 on 2025-05-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0009_favorites_searchstring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('price_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrecoMedioApp.pricetracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FavoritesProduct',
                'unique_together': {('user', 'price_tracker')},
            },
        ),
        migrations.CreateModel(
            name='FavoritesSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FavoritesSearch',
                'unique_together': {('user', 'search_string')},
            },
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
