version: '3.12'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - ALLOWED_HOSTS=localhost
