# Generated by Django 5.0.4 on 2024-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrecoMedioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetracker',
            name='DateOfSearch',
            field=models.DateTimeField(),
        ),
    ]
