# Generated by Django 5.0.4 on 2024-04-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Model', models.CharField(max_length=100)),
                ('StorageGB', models.IntegerField()),
                ('Brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=100)),
                ('DateOfSearch', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SearchString', models.CharField(max_length=100)),
                ('Supplier', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrecoMedioApp.products')),
            ],
        ),
    ]
